[supervisord]
nodaemon=true
logfile=%(ENV_LOG_DIR)s/supervisord-netns.log
pidfile=%(ENV_LOG_DIR)s/supervisord-netns.pid

[inet_http_server]
port=*:9002

[program:O0]
command=ip netns exec O0 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/origin -nodeId O0 -listenAddr 0.0.0.0:8888 -siteDir %(ENV_SRC_DIR)s/origin/sites/a
directory=%(ENV_SRC_DIR)s/origin
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/O0.log
redirect_stderr=true

[program:O1]
command=ip netns exec O1 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/origin -nodeId O1 -listenAddr 0.0.0.0:8888 -siteDir %(ENV_SRC_DIR)s/origin/sites/b
directory=%(ENV_SRC_DIR)s/origin
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/O1.log
redirect_stderr=true

[program:O2]
command=ip netns exec O2 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/origin -nodeId O2 -listenAddr 0.0.0.0:8888 -siteDir %(ENV_SRC_DIR)s/origin/sites/c
directory=%(ENV_SRC_DIR)s/origin
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/O2.log
redirect_stderr=true

[program:C0]
command=ip netns exec C0 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/popcache -nodeId C0 -listenAddr 0.0.0.0:8889 -originConfigPath %(ENV_SRC_DIR)s/origin/origin_config.json -edgeConfigPath %(ENV_SRC_DIR)s/popcache/edge_config.json -shieldConfigPath %(ENV_SRC_DIR)s/popcache/shield_config.json

directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C0.log
redirect_stderr=true

[program:C1]
command=ip netns exec C1 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/popcache -nodeId C1 -listenAddr 0.0.0.0:8889 -originConfigPath %(ENV_SRC_DIR)s/origin/origin_config.json -edgeConfigPath %(ENV_SRC_DIR)s/popcache/edge_config.json -shieldConfigPath %(ENV_SRC_DIR)s/popcache/shield_config.json

directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C1.log
redirect_stderr=true

[program:C2]
command=ip netns exec C2 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/popcache -nodeId C2 -listenAddr 0.0.0.0:8889 -originConfigPath %(ENV_SRC_DIR)s/origin/origin_config.json -edgeConfigPath %(ENV_SRC_DIR)s/popcache/edge_config.json -shieldConfigPath %(ENV_SRC_DIR)s/popcache/shield_config.json
directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/C2.log
redirect_stderr=true

[program:S0]
command=ip netns exec S0 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/shield -nodeId S0 -listenAddr 0.0.0.0:8890 -originConfigPath %(ENV_SRC_DIR)s/popcache/origin_config.json -shieldConfigPath %(ENV_SRC_DIR)s/popcache/shield_config.json
directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/S0.log
redirect_stderr=true

[program:S1]
command=ip netns exec S1 sudo -u %(ENV_MY_USER)s %(ENV_BIN_DIR)s/shield -nodeId S1 -listenAddr 0.0.0.0:8890 -originConfigPath %(ENV_SRC_DIR)s/popcache/origin_config.json -shieldConfigPath %(ENV_SRC_DIR)s/popcache/shield_config.json
directory=%(ENV_SRC_DIR)s/popcache
autostart=true
autorestart=true
startsecs=5
stdout_logfile=%(ENV_LOG_DIR)s/S1.log
redirect_stderr=true

